package com.sample

import java.util.ArrayList;
import java.util.Arrays;

declare enum QuestionVal
	THEME("Does the theme matter to you?", ["Yes"]),
	FAV_THEME("What's your favourite theme?", ["Science Fiction", "Fantasy", "City Building"]),
	DUNGEON_CRAWLING("Do you want a dungeon crawling adventure?", ["Yes", "No"]),
	SERIOUS("A serious one?", ["Yes", "No"]),
	PLAYERS_NUMBER("How many players?", ["Just the two of us", "More then two"]),
	CRUSH_MANEUVER("Crush or out-maneuver your enemies", ["Fight", "Maneuver"]),
	COOPERATIVE_COMPETITIVE_2OPTIONS("Cooperative or Competitive", ["Cooperative", "Competitive"]),
	WITH_KIDS("Playing with kids", ["Yes", "No"]),
	CAMPAIGN("Do you want a campaign", ["Yes", "Just one game"]),
	MANAGING_DUNGEON("How about managin your own dungeon?", ["Yes", "No"]),
	QUESTS("Want the whole questing thing", ["Yes", "No"]),
	COOPERATIVE_COMPETITIVE_3OPTIONS("Cooperative or Competitive", ["Cooperative", "Competitive", "Cooperative - if I can backstab"]),
	RANDOM_EVENTS("Mind getting trounced by random events", ["Yes, Strategy matters", "No, It's the experience that counts"]),
	BOARD_CARD("Board game or Card game", ["Boards", "Cards"]),
	STORYTELLING("Is storytelling important", ["Yes", "Not as much as combat!"]),
	DECKBUILDERS("Do you like Deckbuilders", ["Yes", "No"]),
	COMPETITIVE_DECKS("Competitive deck builders?", ["Competitive", "Cooperative"]),
	LOTR_FAN("Lord of the Ring fan?", ["Yes", "No"]),
	CASTLE_DEFENSE("How about castle defense?", ["Sounds fun", "Not for me"]),
	CONQUEST_FANTASY("Conquest in a fantasy world?", ["Yes", "No"]),
	EPIC("Epic?", ["Yes! It's gotta be big", "No, keep it quick"]),
	EVERDAY_LIFE("Everday life, eh?", ["Running a businnes", "Relaxing after work", "Annihilating your business rivals"]),
	SW("Star Wars fan", ["Yes", "No"]),
	ST("Star Trek, then?", ["Yes", "No"]),
	SW_FAN("Grant adventure or tactical space combat?", ["Adventure", "Pew! Pew!"]),
	ST_FAN("One-on-one or working together?", ["Cooperative", "Competitive"]),
	BATTLESTAR("Battlestar Galactica?", ["Yes", "No"]),
	EEEE("Explore, Expand, Exploit and Exterminate?", ["Of course!", "That's Not right!"]),
	HOW_EPIC("So, just how epic are we getting?", ["We've got all day", "It's a work night..."]),
	ALIEN_RACE("How about an alien race?", ["Maybe Not", "That sounds fun"]),
	BATTLE("Doing battle...", ["In space", "For the Galactic Centre", "For Earth!"]),
	CARD_GAME("How about a card game?", ["Sure, that works", "I like my boards"]),
	SPACE_DECKBUILDER("A Deck Builder?", ["Yes", "No"]),
	LCG("A Living Card Game?", ["Yes", "No"]),
	NOT_ALIEN("If Not alien, I'll be a ...", ["Athlete", "Galastic Corporation", "Space Crew on Mission", "Merchant"]),
	SPACE_CREW("How will you succeed?", ["Teamwork and high-speed planning", "Teamwork and dexterity"]),
	MERCHANT("Seriously?", ["It's serious business", "Nah, we just want a giggle"]),
	CITY_BUILDING("Do you enjoy tile placement?", ["Yes", "No"]),
	ELECTIONS("Are willing to deal with elections?", ["It's the democratic way", "Nope, I just want to build"]),
	SCRATCH_RENEWAL("Starting from scratch or urban renewal?", ["Let's build it up!", "Let's clean the streets!"]);
	 
	question : String
	answers : java.util.List
end 