package com.sample

import java.util.ArrayList;
import java.util.Arrays;

declare Answer
	question : String
	answer : String
end

rule init
when
then
	String ans = QuestionWindow.updateFrame(QuestionVal.THEME.getQuestion(), QuestionVal.THEME.getAnswers());
	insert(new Answer(QuestionVal.THEME.getQuestion(), ans));
end

rule test
when
	a: Answer(a.answer == "YES")
then
	String ans = QuestionWindow.updateFrame("Yes", QuestionVal.THEME.getAnswers());	
end

